"""Evidence-grounded synthesis for the LLM module CLI."""

from __future__ import annotations

import json
import re
from typing import Any

from .faithfulness import check_generation
from .runtime import GenerationResult
from .schemas import validate_analysis_result, validate_parsed_paper, validate_rag_evidence_pack


def _source_lookup(pack: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {snippet["source_id"]: snippet for snippet in pack["evidence_snippets"]}


def _generated_text(result: GenerationResult) -> str:
    """Return backend text or an explicit failure message without fake fallback output."""
    if result.error:
        return f"Generation failed: {result.error}"
    if result.text.strip():
        return result.text.strip()
    return "Generation failed: the backend returned no text."


def _strip_outer_markdown_fence(text: str) -> str:
    """Remove a single outer Markdown fence while preserving inner content."""
    stripped = text.strip()
    match = re.fullmatch(
        r"```(?:markdown|md)?\s*\n(?P<body>.*)\n```",
        stripped,
        flags=re.DOTALL | re.IGNORECASE,
    )
    return match.group("body").strip() if match else stripped


def _verification_lines(audit: dict[str, Any] | None) -> list[str]:
    if not audit or not audit.get("verification_used"):
        return []
    lines = [
        "",
        "## LLM Verification Pass",
        "",
        f"- Verification revised the draft: **{audit.get('verification_revised', False)}**.",
        f"- Verifier supported flag: **{audit.get('supported', False)}**.",
    ]
    unsupported = audit.get("unsupported_claims") or []
    if unsupported:
        lines.append(
            "- Unsupported claims flagged: "
            + "; ".join(str(item) for item in unsupported[:8])
        )
    if audit.get("error"):
        lines.append(f"- Verifier error: {audit['error']}.")
    lines.append(
        "- Same-model verification; combine with deterministic audit and human spot checks."
    )
    lines.append("")
    return lines


def synthesize_markdown(
    pack: dict[str, Any],
    style: str,
    result: GenerationResult,
    *,
    verification_audit: dict[str, Any] | None = None,
) -> str:
    """Render a RAG synthesis and verification report."""
    validate_rag_evidence_pack(pack)
    snippets = _source_lookup(pack)
    source_list = ", ".join(sorted(snippets))
    recommendations = pack["candidates"]
    generated_text = _strip_outer_markdown_fence(_generated_text(result))
    backend_line = (
        f"**Generation backend:** {result.backend}  \n"
        f"**Model:** {result.model}  \n"
        f"**Latency:** {result.latency_seconds}s  \n"
        f"**Generation error:** {result.error or 'none'}"
    )

    lines = [
        "# LLM Synthesis",
        "",
        "**AI disclosure:** This narrative is AI-generated by the local LLM module (`modules/llm`). "
        "It is constrained to the supplied `RagEvidencePack`; unsupported claims are marked "
        "as assumptions or omitted.",
        "",
        f"**Query:** {pack['query']}",
        f"**Retrieval mode:** {pack['retrieval_mode']}",
        f"**Style:** {style}",
    ]
    lines.extend(["", backend_line])
    lines.extend(
        [
            "",
            "## Generated Analysis",
            "",
            generated_text,
            "",
            "## Recommendations From Metadata",
            "",
            "| Rank | Relation | Paper | Evidence | Why it matters | APA citation |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for rank, recommendation in enumerate(recommendations, start=1):
        evidence = ", ".join(recommendation["evidence"])
        paper = recommendation["paper"]
        lines.append(
            f"| {rank} | {recommendation['relation']} | {paper['title']} | {evidence} | "
            f"{recommendation['reason']} | {recommendation['apa_citation']} |"
        )

    verification = check_generation(generated_text, pack)
    lines.extend(
        [
            "",
            "## Deterministic Verification Audit",
            "",
            f"- Source IDs available in evidence pack: {source_list}.",
            f"- Source IDs used by generated answer: {', '.join(verification['used_source_ids']) or 'none'}.",
            f"- Unsupported source IDs: {', '.join(verification['unsupported_source_ids']) or 'none'}.",
            "- APA strings in the recommendation table were copied from `Recommendation.apa_citation`; no DOI or venue was invented by this renderer.",
        ]
    )
    lines.extend(_verification_lines(verification_audit))
    lines.append("")
    return "\n".join(lines)


def summarize_paper_markdown(
    paper: dict[str, Any],
    style: str,
    result: GenerationResult,
    *,
    verification_audit: dict[str, Any] | None = None,
) -> str:
    """Render a paper-only summary with an explicit no-retrieval disclosure."""
    validate_parsed_paper(paper)
    metadata = paper["metadata"]
    sections = paper["sections"]
    generated_text = _strip_outer_markdown_fence(_generated_text(result))
    backend_lines = [
        f"**Generation backend:** {result.backend}  ",
        f"**Model:** {result.model}  ",
        f"**Latency:** {result.latency_seconds}s  ",
        f"**Generation error:** {result.error or 'none'}",
    ]

    lines = [
        "# Paper Summary",
        "",
        "**AI disclosure:** This summary is AI-generated from the supplied `ParsedPaper` only.",
        "",
        "**Evidence scope:** No external evidence or retrieval was used. No `RagEvidencePack` "
        "was created or loaded.",
        "",
        f"**Paper:** {metadata['title']}",
        f"**Style:** {style}",
    ]
    lines.extend(["", *backend_lines])
    lines.extend(["", "## Generated Summary", "", generated_text, ""])
    lines.extend(_verification_lines(verification_audit))
    if not sections.get("abstract") and not metadata.get("abstract"):
        lines.extend(
            [
                "## Input Warning",
                "",
                "The supplied ParsedPaper does not contain abstract text.",
                "",
            ]
        )
    return "\n".join(lines)


def review_paper_markdown(
    paper: dict[str, Any],
    style: str,
    result: GenerationResult,
    *,
    verification_audit: dict[str, Any] | None = None,
) -> str:
    """Render a paper-only peer review with an explicit evidence boundary."""
    validate_parsed_paper(paper)
    generated_text = _strip_outer_markdown_fence(_generated_text(result))
    lines = [
        "# Paper Peer Review",
        "",
        "**AI disclosure:** This review is AI-generated from the supplied `ParsedPaper` only.",
        "",
        "**Evidence scope:** No external evidence, retrieval, or model-memory citation was used.",
        "",
        f"**Paper:** {paper['metadata']['title']}",
        f"**Style:** {style}",
        "",
        f"**Generation backend:** {result.backend}  ",
        f"**Model:** {result.model}  ",
        f"**Latency:** {result.latency_seconds}s  ",
        f"**Generation error:** {result.error or 'none'}",
        "",
        "## Generated Review",
        "",
        generated_text,
        "",
    ]
    lines.extend(_verification_lines(verification_audit))
    return "\n".join(lines)


PARSE_FAILED_SUMMARY = (
    "Synthesis parse failed; see outputs/llm_generation.json for raw model text."
)

_EMPTY_PEER_REVIEW = {
    "strengths": [],
    "weaknesses": [],
    "missing_evidence": [],
    "suggested_improvements": [],
}


def _coerce_str_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return []


def _extract_json_object(text: str) -> dict[str, Any] | None:
    text = text.strip()
    if not text:
        return None
    try:
        parsed = json.loads(text)
        return parsed if isinstance(parsed, dict) else None
    except json.JSONDecodeError:
        pass
    start = text.find("{")
    if start < 0:
        return None
    depth = 0
    for idx in range(start, len(text)):
        ch = text[idx]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                try:
                    parsed = json.loads(text[start : idx + 1])
                    return parsed if isinstance(parsed, dict) else None
                except json.JSONDecodeError:
                    return None
    return None


def _coerce_findings(value: Any) -> list[str]:
    if isinstance(value, dict):
        return [str(v).strip() for v in value.values() if str(v).strip()]
    return _coerce_str_list(value)


def _markdown_heading(line: str) -> tuple[str, int] | None:
    """Return normalized title and level for ATX or bold-only headings."""
    stripped = line.strip()
    atx = re.fullmatch(r"(#{1,6})\s+(.+?)\s*#*", stripped)
    if atx:
        title = re.sub(r"[*_`]", "", atx.group(2)).strip().rstrip(":").lower()
        return title, len(atx.group(1))
    bold = re.fullmatch(r"\*\*(.+?)\*\*\s*:?", stripped)
    if bold:
        title = re.sub(r"[*_`]", "", bold.group(1)).strip().rstrip(":").lower()
        return title, 2
    return None


def _markdown_heading_title(line: str) -> str | None:
    heading = _markdown_heading(line)
    return heading[0] if heading else None


def _section_text(text: str, heading_keywords: tuple[str, ...]) -> str:
    """Extract body text under the first Markdown heading matching a keyword."""
    lines = text.splitlines()
    collected: list[str] = []
    in_section = False
    section_level = 0
    for line in lines:
        heading = _markdown_heading(line)
        if heading is not None:
            title, level = heading
            if any(keyword in title for keyword in heading_keywords):
                in_section = True
                section_level = level
                continue
            if in_section and level <= section_level:
                break
            if in_section:
                collected.append(line)
            continue
        if in_section:
            collected.append(line)
    return "\n".join(collected).strip()


def _bullet_lines(block: str) -> list[str]:
    items: list[str] = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith(("-", "*")) and len(stripped) > 2:
            items.append(stripped.lstrip("-* ").strip())
    return items


def _section_items(
    text: str,
    heading_keywords: tuple[str, ...],
    *,
    label: str,
) -> list[str]:
    block = _section_text(text, heading_keywords)
    if not block:
        return []
    bullets = _bullet_lines(block)
    if bullets:
        return [re.sub(r"\s+", " ", item)[:1000] for item in bullets[:8]]
    compact = re.sub(r"\s+", " ", block).strip()
    return [f"{label}: {compact[:1000]}"] if compact else []


def parse_paper_summary(result: GenerationResult | None) -> dict[str, Any]:
    """Map a paper-only generation into the integration summary contract."""
    if result is None:
        return {
            "summary": "Generation failed: no generation result was returned.",
            "key_findings": [],
            "research_gaps": [],
        }
    generated_text = _strip_outer_markdown_fence(_generated_text(result))
    if result.error:
        return {
            "summary": generated_text,
            "key_findings": [],
            "research_gaps": [],
        }
    key_findings = [
        *_section_items(
            generated_text,
            ("core contribution", "contribution"),
            label="Core contribution",
        ),
        *_section_items(generated_text, ("results", "findings"), label="Results"),
    ]
    research_gaps = _section_items(
        generated_text,
        ("limitations", "research gaps", "missing evidence"),
        label="Limitations",
    )
    return {
        "summary": generated_text,
        "key_findings": key_findings[:12],
        "research_gaps": research_gaps[:12],
    }


def parse_paper_review(result: GenerationResult | None) -> dict[str, str]:
    """Map a paper-only review generation into a stable integration payload."""
    if result is None:
        return {"peer_review": "Generation failed: no generation result was returned."}
    return {"peer_review": _strip_outer_markdown_fence(_generated_text(result))}


def _fields_from_markdown_fallback(text: str) -> dict[str, Any] | None:
    """Best-effort mapping when the model returns prose instead of JSON."""
    stripped = text.strip()
    if len(stripped) < 80:
        return None
    has_heading = any(
        _markdown_heading_title(line) is not None for line in stripped.splitlines()
    )
    if not has_heading and "\n-" not in stripped:
        if stripped.startswith(("{", "[")):
            return None
        return {
            "summary": re.sub(r"\s+", " ", stripped),
            "key_findings": [],
            "research_gaps": [],
        }
    conclusion = _section_text(text, ("conclusion", "summary"))
    findings_block = _section_text(text, ("findings", "key findings"))
    gaps_block = _section_text(
        text,
        ("assumptions", "research gaps", "gaps", "limitations"),
    )

    key_findings = _bullet_lines(findings_block)
    if findings_block and not key_findings:
        key_findings = [
            re.sub(r"\s+", " ", chunk).strip()
            for chunk in re.split(r"\n#{3,6}\s+", findings_block)
            if chunk.strip()
        ]

    research_gaps = _bullet_lines(gaps_block)
    summary = conclusion
    if not summary:
        leading_lines: list[str] = []
        for line in stripped.splitlines():
            if _markdown_heading_title(line) is not None:
                break
            if line.strip().startswith(("-", "*")):
                break
            leading_lines.append(line)
        summary = re.sub(r"\s+", " ", "\n".join(leading_lines)).strip()
    if not summary and not key_findings and not research_gaps:
        return None
    return {
        "summary": summary,
        "key_findings": key_findings[:12],
        "research_gaps": research_gaps[:12],
    }


def _fields_from_parsed(obj: dict[str, Any]) -> dict[str, Any]:
    summary = obj.get("summary") or obj.get("abstract") or ""
    summary = str(summary).strip() if summary is not None else ""
    key_findings = _coerce_findings(obj.get("key_findings") or obj.get("findings"))
    research_gaps = _coerce_str_list(obj.get("research_gaps") or obj.get("gaps"))
    if not summary and key_findings:
        summary = key_findings[0]
    return {
        "summary": summary,
        "key_findings": key_findings,
        "research_gaps": research_gaps,
    }


def parse_topic_synthesis(result: GenerationResult | None) -> dict[str, Any]:
    """Parse model JSON into summary / key_findings / research_gaps for topic mode."""
    failed = {
        "summary": PARSE_FAILED_SUMMARY,
        "key_findings": [],
        "research_gaps": [],
    }
    if result is None or not result.text.strip():
        if result and result.error:
            failed["summary"] = f"Synthesis failed: {result.error}"
        return failed
    if result.error:
        return {
            "summary": f"Synthesis failed: {result.error}",
            "key_findings": [],
            "research_gaps": [],
        }
    parsed_obj = _extract_json_object(result.text)
    if parsed_obj:
        fields = _fields_from_parsed(parsed_obj)
    else:
        fallback = _fields_from_markdown_fallback(result.text)
        if not fallback:
            return failed
        fields = fallback
    if not fields["summary"] and not fields["key_findings"] and not fields["research_gaps"]:
        return failed
    if not fields["summary"]:
        fields["summary"] = PARSE_FAILED_SUMMARY
    return fields


def analysis_result_from_pack(pack: dict[str, Any], result: GenerationResult | None = None) -> dict[str, Any]:
    validate_rag_evidence_pack(pack)
    synthesis = parse_topic_synthesis(result)
    result_obj = {
        "input_type": "topic_text",
        "paper": None,
        "query": pack["query"],
        "summary": synthesis["summary"],
        "key_findings": synthesis["key_findings"],
        "research_gaps": synthesis["research_gaps"],
        "recommendations": pack["candidates"],
        "peer_review": dict(_EMPTY_PEER_REVIEW),
        "evidence_sources": [snippet["source_id"] for snippet in pack["evidence_snippets"]],
    }
    validate_analysis_result(result_obj)
    return result_obj


def _paper_year(paper: dict[str, Any]) -> str | None:
    date = paper.get("published_date") or paper.get("update_date") or ""
    if isinstance(date, str) and len(date) >= 4:
        return date[:4]
    return None


def _snippet_for_paper(
    paper_id: str,
    evidence_pack: dict[str, Any],
    paper: dict[str, Any],
) -> str:
    for snippet in evidence_pack.get("evidence_snippets", []):
        if snippet.get("source_id") == paper_id:
            text = str(snippet.get("snippet") or "").strip()
            if text:
                return text
    abstract = str(paper.get("abstract") or "").strip()
    if len(abstract) > 300:
        return abstract[:300].rstrip() + "..."
    return abstract


def parse_paper_recommendation_summaries(
    result: GenerationResult | None,
) -> dict[str, str]:
    """Parse source_id -> summary mappings from model output."""
    summaries: dict[str, str] = {}
    if result is None or result.error or not result.text.strip():
        return summaries
    parsed_obj = _extract_json_object(result.text)
    if not parsed_obj:
        return summaries
    if isinstance(parsed_obj.get("paper_summaries"), list):
        for item in parsed_obj["paper_summaries"]:
            if not isinstance(item, dict):
                continue
            source_id = str(item.get("source_id") or "").strip()
            summary = str(item.get("summary") or "").strip()
            if source_id and summary and source_id not in summaries:
                summaries[source_id] = summary
    elif isinstance(parsed_obj.get("summaries"), dict):
        for source_id, summary in parsed_obj["summaries"].items():
            sid = str(source_id).strip()
            text = str(summary).strip()
            if sid and text and sid not in summaries:
                summaries[sid] = text
    return summaries


def resolve_paper_summary(
    paper_id: str,
    summaries: dict[str, str],
    evidence_pack: dict[str, Any],
    paper: dict[str, Any],
) -> str:
    """Use a validated LLM summary or fall back to Bank's abstract snippet."""
    summary = summaries.get(paper_id, "").strip()
    if summary:
        return summary
    return _snippet_for_paper(paper_id, evidence_pack, paper)


def build_recommended_paper_cards(
    raw_recommendations: list[dict[str, Any]],
    summaries: dict[str, str],
    evidence_pack: dict[str, Any],
    *,
    max_papers: int = 5,
) -> list[dict[str, Any]]:
    """Merge Bank metadata with validated per-paper summaries."""
    valid_ids = {
        str(snippet.get("source_id") or "")
        for snippet in evidence_pack.get("evidence_snippets", [])
        if snippet.get("source_id")
    }
    selected = raw_recommendations[:max_papers]
    allowed_ids = {
        str((rec.get("paper") or {}).get("paper_id") or (rec.get("paper") or {}).get("id") or "")
        for rec in selected
    }
    filtered_summaries = {
        source_id: text
        for source_id, text in summaries.items()
        if source_id in allowed_ids and source_id in valid_ids
    }

    cards: list[dict[str, Any]] = []
    for rec in selected:
        paper = rec.get("paper") or {}
        paper_id = str(paper.get("paper_id") or paper.get("id") or "")
        authors = paper.get("authors", [])
        if not isinstance(authors, list):
            authors = [str(authors)] if authors else []
        cards.append(
            {
                "paper_id": paper_id,
                "title": paper.get("title", ""),
                "authors": authors,
                "year": _paper_year(paper),
                "url": paper.get("url", ""),
                "score": float(rec.get("score", 0.0)),
                "apa_citation": rec.get("apa_citation", ""),
                "summary": resolve_paper_summary(
                    paper_id,
                    filtered_summaries,
                    evidence_pack,
                    paper,
                ),
            }
        )
    return cards


def handoff_markdown() -> str:
    return """# LLM module handoff

## What This Module Produces

- `outputs/llm_analysis.md`: evidence-grounded synthesis from a `RagEvidencePack`.
- `outputs/analysis_result_from_llm.json`: `AnalysisResult`-compatible JSON for integration CLI/API.
- `outputs/llm_generation.json`: generation metadata for the latest synthesis run.
- `data/eval/fixed_prompts.jsonl`: six fixed prompts for repeatable comparison.
- `results/prompt_comparison/`: Ollama-backed prompt strategy evidence from `compare-prompts`.
- `results/model_comparison/`: model, adapter, quantization, and comparison evidence.

## How Integration Should Consume It

1. `modules/retrieval` writes `outputs/rag_evidence_pack.json`.
2. Run `python -m app.cli synthesize --evidence outputs/rag_evidence_pack.json --style technical --out outputs/llm_analysis.md`.
3. For final model evidence, pass `--model <tag>` when comparing adapters.
4. Render `outputs/llm_analysis.md` in CLI/UI, or consume `outputs/analysis_result_from_llm.json`.

## Current Limitation

Proxy mode is only a deterministic smoke-test path. Report claims about output quality,
latency, quantization, or adapter improvement must use Ollama/model-comparison artifacts
created from real local model tags.
"""
